--liquibase formatted sql
--changeset Gangadhar Nitta:02-create-email-bounce-report-table.sql
CREATE TABLE IF NOT EXISTS crime_application_tracking.EMAIL_BOUNCE_REPORT
(	ID SERIAL PRIMARY KEY,
    TIME_STAMP VARCHAR(40) NOT NULL,
    MAAT_ID INTEGER NOT NULL,
    RECIPIENT_EMAIL_ADDRESS VARCHAR(255) NOT NULL,
    BOUNCE_TYPE VARCHAR(50) NOT NULL,
    BOUNCE_SUB_TYPE VARCHAR(50) NOT NULL,
    ERROR_MESSAGE VARCHAR(200) NOT NULL
);