--liquibase formatted sql
--changeset Josh Hunt:07-create-application-decision-history-table.sql

CREATE TABLE IF NOT EXISTS crime_application_tracking.APPLICATION_DECISION_HISTORY
(
    ID SERIAL PRIMARY KEY,
    USN INTEGER NOT NULL,
    REP_ID INTEGER NOT NULL,
    DATE_RESULT_CREATED TIMESTAMP NOT NULL,
    CASE_ID VARCHAR(20),
    DATE_APP_CREATED DATE,
    IOJ_RESULT VARCHAR(4),
    IOJ_ASSESSOR_NAME VARCHAR(100),
    IOJ_REASON VARCHAR(1000),
    MEANS_RESULT VARCHAR(50),
    MEANS_ASSESSOR_NAME VARCHAR(100),
    DATE_MEANS_CREATED DATE,
    FUNDING_DECISION VARCHAR(50),
    PASSPORT_RESULT VARCHAR(50),
    PASSPORT_ASSESSOR_NAME VARCHAR(100),
    DATE_PASSPORT_CREATED DATE,
    DWP_RESULT VARCHAR(20),
    IOJ_APPEAL_RESULT VARCHAR(4),
    HARDSHIP_RESULT VARCHAR(4),
    CASE_TYPE VARCHAR(20),
    REP_DECISION VARCHAR(50),
    CC_REP_DECISION VARCHAR(50),
    ASSESSMENT_ID INTEGER,
    ASSESSMENT_TYPE VARCHAR(20),
    WROTE_TO_RESULTS VARCHAR(1),
    MAGS_OUTCOME VARCHAR(20)
);
    