apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-crime-application-tracking-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laa-crime-application-tracking-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if not (eq (toString .Values.actuator.port) "http") }}
    - port: {{ .Values.actuator.port }}
      targetPort: actuator
      protocol: TCP
      name: actuator
    {{- end }}
  selector:
    {{- include "laa-crime-application-tracking-service.selectorLabels" . | nindent 4 }}
