# Default values for laa-crime-application-tracking-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-apps-team/laa-crime-application-tracking-service-dev
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest

sentry:
  sampleRate: 0.05

aws_region: eu-west-2

java:
  host_env: uat

jwt:
  issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_cuKi4RLL5

maatApi:
  baseUrl: https://maat-cd-api.uat.legalservices.gov.uk/api
  oauthUrl: https://maat-cd-api-uat.auth.eu-west-2.amazoncognito.com/oauth2/token
  registrationId: maatapi
  oauthScope: maat-cd-api/standard

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  name: "crime-application-tracking"

service:
  type: ClusterIP
  port: 80
  targetPort: 8490

ingress:
  environmentName:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: "laa-crime-application-tracking-service-laa-crime-application-tracking-service-uat-green"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecAuditEngine On
      SecRuleEngine DetectionOnly
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-crime-apps-team,tag:namespace=laa-crime-application-tracking-service-uat"
  externalAnnotations: {}
  hosts:
    - host: laa-crime-application-tracking-service-uat.apps.live.cloud-platform.service.justice.gov.uk
      paths: ["/"]
  tls: []
  className: modsec-non-prod

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

actuator:
  metrics:
    enabled: true
    scrapeInterval: 15s
    path: /actuator/prometheus
  health:
    path: /actuator/health
  port: 8500
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5

scheduledDowntime:
  enabled: true
  # Start at 6am UTC Monday-Friday
  startup: '0 6 * * 1-5'
  # Stop at 10pm UTC Monday-Friday
  shutdown: '0 22 * * 1-5'
  serviceAccountName: scheduled-downtime-serviceaccount

cloudPlatform:
  aws:
    sqs:
      region: eu-west-2
      enabled: true
      queue:
        email_notifications: laa-crime-apps-team-uat-process-email-notifications-queue
