# Default values for laa-crime-application-tracking-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-apps-team/laa-crime-application-tracking-service-dev
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest

sentry:
  sampleRate: 1.0

aws_region: eu-west-2

java:
  host_env: production

jwt:
  issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_cuKi4RLL5

maatApi:
  baseUrl: https://laa-maat-data-api-prod.apps.live.cloud-platform.service.justice.gov.uk/api
  oauthUrl: https://maat-api-prod.auth.eu-west-2.amazoncognito.com/oauth2/token
  registrationId: maatapi
  oauthScope: maat-api-prod/standard

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  name: "crime-application-tracking"

service:
  type: ClusterIP
  port: 80
  targetPort: 8490

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

actuator:
  metrics:
    enabled: true
    scrapeInterval: 15s
    path: /actuator/prometheus
  health:
    path: /actuator/health
  port: 8500
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5

scheduledDowntime:
  enabled: false

cloudPlatform:
  aws:
    sqs:
      region: eu-west-2
      enabled: true
      queue:
        email_notifications: laa-crime-apps-team-production-process-email-notifications-queue
