version: "3.5"

services:
  app:
    environment:
      - SENTRY_ENV=development
      - SENTRY_SAMPLE_RATE=0.0
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8383"

    env_file:
      - app.env

    ports:
      - "8383:8383"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8383 -jar app.jar

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crime_application_tracking

networks:
  local-container-network:
    driver: bridge
    name: local-container-network
